### ISSUE TITLE
Error during docker-compose on Ubuntu 18.04

### ISSUE THREAD

**Issue by brenojac** [ellakcy/moodle-compose#2]
Hello,

I'm trying to use your docker-compose file to run a Moodle instance with Nginx and PostgreSQL on Ubuntu 18.04. I'm getting the following error when running docker-compose up -d: 

root@educationexperience:~/dockercompose/moodle-compose# docker-compose up -d
WARNING: The moodle variable is not set. Defaulting to a blank string.
WARNING: The guintera_mdluser variable is not set. Defaulting to a blank string.
WARNING: The lnxr0x variable is not set. Defaulting to a blank string.
Starting moodle-compose_moodle_db_1 ... done
Starting moodle-compose_moodle_1    ... error

ERROR: for moodle-compose_moodle_1  Cannot start service moodle: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/local/bin/entrypoint.sh\": permission denied": unknown

ERROR: for moodle  Cannot start service moodle: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/local/bin/entrypoint.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.

   I tried to locate the entrypoint.sh file to that I could fix this apparent permission error, but I was unable to find it. I searched on google and similar errors are permission related, but some tinkering on the Dockerfile is necessary, which I was not able to find either. Could you give me a hint on solving this issue? 

    Thanks in advance and thank you for the great work in this github project. 

regards, 

- Breno

**Comment by pc-magas** [comment]
Hello the `entrypoint.sh` is located inside the image itself. I guess I do something wrong during the image building in https://github.com/ellakcy/docker-moodle . I will fix it as fast as I can.

**Comment by brenojac** [comment]
Dear pc-magas,

Thank you for the prompt reply. Will you let me know as soon as are able to fix it so that I can test it again? Thank you.

**Comment by pc-magas** [comment]
Have you tried the apache ones? Does the problem occur in these ones as well?

**Comment by brenojac** [comment]
Hi,

I have tried the apache one and it's doing fine. I prefer nginx as a web server. I consider it more robust. But if the problem is not solvable in the short term, I might stick to the apache image as well. 

I'm getting connection reset while trying to test the image on port 8082, but as I search it seems to be more of a docker issue. 

thanks and best regards,

- Breno

**Comment by pc-magas** [comment]
I did some changes on the fpm-images try to use the fpm via following steps:

1. `docker-compose down -v`
1. Set the docker-compose.yml into the fpm-postgresql one.
2. And then run:
    ```
      docker-compose pull
    ```
3. Afterwards run:
    ```
      docker-compose down -v && docker-compose up -d
    ```

I did a fix on alpine-fpm. I assume the connection reser problem is via the following 2 issues:

1. Incorrect url
2. Corrupted volume

What url do you type in order to be able to access the moodle?

**Comment by brenojac** [comment]
Hello @pc-magas ,

I did just as you said and still got the same error: 

```
root@brenojac-Inspiron-3437:~/code/moodleenv/moodle-compose# docker-compose up -d
WARNING: The MOODLE_DB_NAME variable is not set. Defaulting to a blank string.
WARNING: The MOODLE_DB_USER variable is not set. Defaulting to a blank string.
WARNING: The MOODLE_DB_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The MOODLE_URL variable is not set. Defaulting to a blank string.
WARNING: The MOODLE_ADMIN variable is not set. Defaulting to a blank string.
WARNING: The MOODLE_ADMIN_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The MOODLE_ADMIN_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The MOODLE_REVERSE_LB variable is not set. Defaulting to a blank string.
WARNING: The MOODLE_SSL variable is not set. Defaulting to a blank string.
WARNING: The MOODLE_EMAIL_TYPE_QMAIL variable is not set. Defaulting to a blank string.
WARNING: The MOODLE_EMAIL_HOST variable is not set. Defaulting to a blank string.
Creating network "moodle-compose_default" with the default driver
Creating moodle-compose_moodle_db_1 ... done
Creating moodle-compose_moodle_1    ... error

ERROR: for moodle-compose_moodle_1  Cannot start service moodle: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/local/bin/entrypoint.sh\": permission denied": unknown

ERROR: for moodle  Cannot start service moodle: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/local/bin/entrypoint.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.

```
About the apache image, I just try to access the default URL at http://localhost:8082. But as I told you, I'm also getting this error with other images, for example, I can run strapi.io (a headless CMS written in node.js) using docker-compose, perfectly. But I get connection refused when trying to access the container too. Trying to debug to find out what might be causing it. 

If there's anything else I can do to fix the above issue (on the nginx image), please let me know.

**Comment by pc-magas** [comment]
have you placed a .env file to your directory containing `docker-compose.yml` ?

Run:
```
cp .env .env.bak
cp  .env.dist .env
```

And fill the .env with the appropriate values indicated by `#FILL WITH A VALUE`. Also you can perform changes to your setup as well.

**Comment by brenojac** [comment]
Hello,

I got back on this issue, but I was unable to find a solution to the above problem. I tried the other image: docker-compose_postgresql_apache.yml and it runs fine, but the containers is exited as soon as it is started: 

`223ab8eab389        ellakcy/moodle:postgresql_apache   "/usr/local/bin/entr…"   2 minutes ago       Exited (1) 2 minutes ago                                              moodle-compose_moodle_1`

Watching the logs I see this: 
```
Installing moodle with all support
Moving files into web folder
sending incremental file list

sent 603,326 bytes  received 37,427 bytes  256,301.20 bytes/sec
total size is 180,643,651  speedup is 281.92
Fixing files and permissions
Setting up database
No database support found
```

The pgsql DB is up and running: 
`
9168e642c050        postgres:9-alpine                  "docker-entrypoint.s…"   4 minutes ago       Up 4 minutes               5432/tcp                                   moodle-compose_moodle_db_1
`

So I'm not sure what could be missing. I just followed your default docker-compose file. Any ideas?

**Comment by pc-magas** [comment]
Recently I pushed new moodle images try:

```
git pull
docker-compose pull
```

Also try removing any reference of `MOODLE_DB_TYPE` from your `.env`.

**Comment by ivan5rov** [comment]
@pc-magas (my issue got closed #3 ), I tried re-downloading the images and .env does not have reference to `MOODLE_DB_TYPE`, but still I am getting the error about no database support

**Comment by leobg** [comment]
@pc-magas (my issue got closed #3 ), I tried re-downloading the images and .env does not have reference to MOODLE_DB_TYPE, but still I am getting the error about no database support

**Comment by pc-magas** [comment]
@leobg I know but because there's also a reference for this bug here, hence I closed it so we can have all the bug references here.

**Comment by pc-magas** [comment]
I have fixed the `apache_mysql` variant of docker moodle and tested it. 

Please try again via running `docker-compose pull` and `docker-compose up` commands.

I will test other variants as well.

The bug existed in mistaggin in https://github.com/ellakcy/docker-moodle

**Comment by pc-magas** [comment]
I rebuilt the images ans fixed the database issue:
Try:

```
docker-compose pull
docker-compose up -d
```

Ans it should work like a charm!
