### ISSUE TITLE
No database support found

### ISSUE THREAD

**Issue by leobg** [ellakcy/moodle-compose#3]
I am trying to setup the apache_mysql variant, containers get created and stuff initialized, but moodle container can't seem to create the database, exits with the error:

`No database support found`

.env is setup using the dist file (just swapped the values need swapping). Am I missing something?

**Comment by pc-magas** [comment]
Duplicate of https://github.com/ellakcy/moodle-compose/issues/2

**Comment by pc-magas** [comment]
Hello, there were reports that happened again. We did fix the issue and we fixed it again.

Also if does happen this issue consult this: https://github.com/ellakcy/moodle-compose/issues/5#issuecomment-1019492236
Any image builds are timestamped therefore you can rollback to latest working versions.
