### ISSUE TITLE
no database support found

### ISSUE THREAD

**Issue by stiffmaester29** [ellakcy/moodle-compose#4]
currently using the following version

ellakcy/moodle:postgresql__apache_38

please see below logs:

Fixing files and permissions
Installing moodle with  support
No database support found

**Comment by pc-magas** [comment]
Sorry for the late reply.

Rename the `ellakcy/moodle:postgresql__apache_38` into `ellakcy/moodle:postgresql_apache_38`. 

Then run:

```
docker pull ellakcy/moodle:postgresql_apache_38
docker-compose up -d 
```
Then if you see any error in `docker-compose logs -f` regarding the database on moodle container, then report it here.

The `postgresql__apache_38` is no longer maintained (due to a bug in our build system)

**Comment by shadow1runner** [comment]
Hi,

I am facing the very same issue running `master`:

```shell
#[...]
moodle_1     | webservice/xmlrpc/tests/fixtures/array_response.xml
moodle_1     | webservice/xmlrpc/tests/fixtures/fault_response.xml
moodle_1     | webservice/xmlrpc/tests/fixtures/value_response.xml
moodle_1     | 
moodle_1     | sent 201,859,228 bytes  received 415,347 bytes  527,443.48 bytes/sec
moodle_1     | total size is 200,314,964  speedup is 0.99
moodle_1     | Fixing files and permissions
moodle_1     | Installing moodle with  support
moodle_1     | No database support found
moodle_moodle_1 exited with code 1
```
I've been trying to get it work based on your above suggestion using `image: ellakcy/moodle:postgresql_apache_38` but it brings no change whatsoever (master currently features `image: ellakcy/moodle:postgresql_apache`).

I've also tried mysql, mariadb and postgres, all of them show the very same issue, any idea what I can try?

Thanks!

**Comment by pc-magas** [comment]
Hello, there were reports that happened again. We did fix the issue and we fixed it again.

Also if does happen this issue consult this: https://github.com/ellakcy/moodle-compose/issues/5#issuecomment-1019492236
Any image builds are timestamped therefore you can rollback to latest working versions.
