### ISSUE TITLE
`No database support found` (again)

### ISSUE THREAD

**Issue by shadow1runner** [ellakcy/moodle-compose#5]
Hi,

closely related to #4 I am facing the very same issue running `master`:

```shell
#[...]
moodle_1     | webservice/xmlrpc/tests/fixtures/array_response.xml
moodle_1     | webservice/xmlrpc/tests/fixtures/fault_response.xml
moodle_1     | webservice/xmlrpc/tests/fixtures/value_response.xml
moodle_1     | 
moodle_1     | sent 201,859,228 bytes  received 415,347 bytes  527,443.48 bytes/sec
moodle_1     | total size is 200,314,964  speedup is 0.99
moodle_1     | Fixing files and permissions
moodle_1     | Installing moodle with  support
moodle_1     | No database support found
moodle_moodle_1 exited with code 1
```
I've been trying to get it work based on your [suggestion in #4](https://github.com/ellakcy/moodle-compose/issues/4#issuecomment-855265199) using `image: ellakcy/moodle:postgresql_apache_38` but it brings no change whatsoever (master currently features `image: ellakcy/moodle:postgresql_apache`).

I've also tried mysql, mariadb and postgres, all of them show the very same issue, any idea what I can try?

Thanks!

**Comment by pc-magas** [comment]
Thanks for your issue. There was an issue with our build system. New images were pushed try again by running:

```
docker-compose pull
docker-compose up -d
```

In case that this problem occurs again you can use the `ellakcy/moodle:postgresql_apache_38_202201220127` `ellakcy/moodle:postgresql_apache_202201220127` ones. We timestamp our builds in order to offer versioned tags for our images. In this case the timestamp `202201220127` is the latest one that fixes the problem.

**Comment by shadow1runner** [comment]
Thanks for fixing this issue so quickly, @pc-magas!

Works fine now:

```log
moodle_1          | ++ Success ++
moodle_1          | Installation completed successfully.
```

Closing, thanks!

**Comment by pc-magas** [comment]
In case similar issue does happen plz open an issue in https://github.com/ellakcy/docker-moodle and I'll fix it as soon as possible.

Also, the timestamp mentioned above does apply in all flavours and moodle versions. By appending a `_202201220127` may fix any issue. Also, try looking in https://hub.docker.com/r/ellakcy/moodle for the available timestamped builds.

Any image without timestamp will point to the latest build.
