### ISSUE TITLE
version 10 is required and you are running 9.6.24

### ISSUE THREAD

**Issue by adamshand** [ellakcy/moodle-compose#6]
hello,

trying to get moodle running with your docker-compose setup (which looks very nice, thanks!).

i'm having trouble with the apache-postgres setup and am noticing this error in the logs.  not sure if it's just a warning or an error, but thought i'd report it:

```
moodle             | == Environment ==
moodle             | !! database postgres (9.6.24) !!
moodle             | [System] version 10 is required and you are running 9.6.24 -
moodle             |
```

**Comment by pc-magas** [comment]
Did a complete overhaul:

Run:
```
git pull origin master
docker-compose up -d
```

And enjoy.

**Comment by adamshand** [comment]
Thanks!
